### ISSUE TITLE
Removal of hidden "encounter-details" field and default="now" attribute from specific forms

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nmrsmetadata#107]
<div class="hidden" id="encounter-details" sectionTag="section" headerStyle="title" headerLabel="Encounter Details">
</div>

The above code in the html form causes forms to submit with "data entry date" rather than actual visit date of the patient, creating a lot of confusion

**Comment by wandechris** [comment]
Pharmacy forms
Care card
General Antenatal form
PMTCT HTS
HIV Enrollment form
