### ISSUE TITLE
Addition of Next Appointment Date (Concept ID 5096) to the Pharmacy Form

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nmrsmetadata#109]
This will give us a more accurate Missed Appointment Report and also a more accurate Scheduled Appointment Query.

**Comment by wandechris** [comment]
CDC review

**Comment by enumahin** [comment]
What's the conclusion on this issue? should we go ahead and implement it?

**Comment by brightoibe** [comment]
This has been implemented on the pharmacy form alread.

**Comment by brightoibe** [comment]
This is still pending for CDC approval. Appointment booking from pharmacy forms are more accurate than the one from Care Card and are best used for clinic planning.
