### ISSUE TITLE
Spelling error "Virginal thrush"  instead of "Vaginal thrush"

### ISSUE THREAD

**Issue by Nnalda** [nmrs-nigeria/openmrs-module-nmrsmetadata#14]
Spelling error (Virginal thrush) under Other OIs section of the care card. Correct spelling to "Vaginal thrush".

SOLUTION:
Vaginal thrush spelling was to reflect as Virginal thrush

**Comment by teggsdgreat** [comment]
spelling corrected

**Comment by caniekwe** [comment]
This is not corrected. see image below
![Capture](https://user-images.githubusercontent.com/38128659/95594040-57ace500-0a42-11eb-9ba1-0a783a994152.JPG)
