### ISSUE TITLE
Esophageal thrush missing on care card

### ISSUE THREAD

**Issue by Nnalda** [nmrs-nigeria/openmrs-module-nmrsmetadata#15]
Esophageal thrush is not included on the care card, it should be added as a checkbox on the care card. 

SOLUTION:
Added Esophageal thrush as a checkbox

**Comment by caniekwe** [comment]
Can't find this. I guess this is under Other OIs/Problems or Noted Side effect. I don't see esophageal thrush there. Meanwhile, there is a drop down field that was added which I am not sure what that is. 

![Capture](https://user-images.githubusercontent.com/38128659/95593874-1e747500-0a42-11eb-82a4-27d713d30662.JPG)
