### ISSUE TITLE
encounter.encounter_datetime != obs.obs_datetime bug

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nmrsmetadata#215]
This bug is caused by the presence of the following tags

`<div class="hidden" id="encounter-details" sectionTag="section" headerStyle="title" headerLabel="Encounter Details">`
        `<fieldset>
            <legend class="legend_style">When?</legend>
            <label>When?</label>
            <encounterDate default="now" showTime="false" allowFutureDates="false"/>
        </fieldset>`
        `<fieldset>
            <legend>Who?</legend>
            <label>Who?</label>
            <encounterProviderAndRole default="currentUser" encounterRole="240b26f9-dd88-4172-823d-4a8bfeb7841f"                                                     required="true"/>
        </fieldset>`

        `<fieldset>
            <legend>Where?</legend>
            <label>Where?</label>
            <encounterLocation default="SessionAttribute:emrContext.sessionLocationId"/>
        </fieldset>`
    `</div>`

This tag is creating bugs in the following forms;

Lab Order and Result Form
ART Commencement Form
Client Referral Form
Transfer Form

**Comment by talk2morris** [comment]
done. I found similar issue on Discontinuation, PediatricInitial,RequestAndResultForm,IPTForm,PartnerRegistrationForm.
