### ISSUE TITLE
Inclusion of Recency to the PMTCT HTS from

### ISSUE THREAD

**Issue by ahmedsylvanus** [nmrs-nigeria/openmrs-module-nmrsmetadata#219]
We need to have the Recency section of the PMTCT HTS form on NMRS mirror the Recency section on the client intake form. All previous data elements should be removed.

**Comment by brightoibe** [comment]
> 
> 
> We need to have the Recency section of the PMTCT HTS form on NMRS mirror the Recency section on the client intake form. All previous data elements should be removed.
Thank you @ahmedsylvanus for pointing this out. But there has been a conversation around making Recency a stand alone service with its own seperate form. This has to be implemented in 1.0.3 metadata so it does not break the NDR plugin algorithm.

**Comment by ahmedsylvanus** [comment]
Thanks @brightoibe but we received communication that CDC has OK'd this modification to the PMTCT HTS form. Methods are being put in place to take care of referals.

**Comment by talk2morris** [comment]
are we not having this issue been duplicated?..

**Comment by talk2morris** [comment]
I am referring to issue #221

**Comment by talk2morris** [comment]
@ahmedsylvanus kindly if this is true so I can merge into one.

**Comment by ahmedsylvanus** [comment]
The issue is not entirely been duplicated. We need to ensure we have a consensus from the program team before we begin to log issues that require we make modifications. #221 and #219 are contradicting.
