### ISSUE TITLE
ABC-3TC-LPV/r is currently used as a pediatric first-line but it is not included in the EMR as a first-line regimen

### ISSUE THREAD

**Issue by Nnalda** [nmrs-nigeria/openmrs-module-nmrsmetadata#25]
ABC-3TC-LPV/r is currently used as a pediatric first-line but it is not included in the EMR as a first-line regimen. The way forward is to inactivate (NOT DELETE) from the second-line regimen list, and include ABC-3TC-LPV/r on the pediatric first-line regimen list.

SOLUTION:
ABC-3TC-LPV/r was added as an option in pediatric 1st line

**Comment by teggsdgreat** [comment]
ABC-3TC-LPV/r included on the pediatric first-line
