### ISSUE TITLE
TRACKING AND TERMINATION FORM NOT SAVING

### ISSUE THREAD

**Issue by abrahamolatubosun1973** [nmrs-nigeria/openmrs-module-nmrsmetadata#264]
Hi Colleagues,

I believe we are all doing fine and keeping safe.

I just want to establish here that, post deploying the new metadata shared by CCFN we discovered that the Tracking and Termination form refuse to save after ensuring that all form attributes are properly captured.

We hope that the Form development team can look into this and help to fix this bug.

Thank you all

**Comment by wonderfulguru1** [comment]
@abrahamolatubosun1973  thank you for raising this CCFN will check and fix appropraitely.
