### ISSUE TITLE
Recency ID confirmation on client intake form

### ISSUE THREAD

**Issue by Nnalda** [nmrs-nigeria/openmrs-module-nmrsmetadata#3]
Recency ID confirmation does not flag immediately. Allows further data entry until when the form is to be submitted. Recency ID confirmation to flag immediately upon leaving the confirmation field, not later.

SOLUTION:
1. The recency ID is checked if empty or not 
2. It is checked to ensure only alphanumeric data only are entered
3. The verify recency ID field is checked if empty
4. The verify recency ID field is checked if greater than 10 character
5. Finally its checked if the value in both field are equal

**Comment by talk2morris** [comment]
check that the recency ID is of correct format
