### ISSUE TITLE
Pharmacy form saves and submits without key variables

### ISSUE THREAD

**Issue by Nnalda** [nmrs-nigeria/openmrs-module-nmrsmetadata#6]
Sometimes pharmacy forms are saves without Treatment age, regimen line, or even regimen. Include validation rules to check for these entries before submitting the form. While ensuring that ARV entries violations do not prevent OI entries from saving if pharmacy form is saved for only OI drugs.

SOLUTION:
To ensure pharmacy form submits if only OI drugs are filled without ART entries while also ensuring all necessary ART fields are filled if any entry is made for ART
1. OI fields are checked if not empty while ART is empty then prompt user at submission if the ART fields are left empty on purpose
2. If ART fields are field then check to ensure all compulsory fields like duration, regimen, treatment age and regimen line are filed or not

**Comment by teggsdgreat** [comment]
All major ARV fields like treatment age, regimen line, duration and regimen are checked before submitting the form but allows form to submit if only OI drugs are to be submitted

**Comment by talk2morris** [comment]
add validation for OI should be implemented
