### ISSUE TITLE
Implement hard logic for recency interpretation as listed below.

### ISSUE THREAD

**Issue by wandechris** [nmrs-nigeria/openmrs-module-nmrsmetadata#66]
Control Line | Verification Line | Long-Term Line | Correct Interpretation
-- | -- | -- | --
Yes | Yes | Yes | Long-Term
Yes | Yes | No | Recent
Yes | No | No | Negative
Yes | No | Yes | Invalid
No | Yes | Yes | Invalid
No | No | No | Invalid
No | No | Yes | Invalid
No | Yes | No | Invalid

@Nnalda @teggsdgreat

**Comment by tobstech** [comment]
I remembered implementing this last year. Requested by Wande & Ahmed.
