### ISSUE TITLE
Key information like Patient Current Regimen, Last Pick Up Date, Treatment Age, and Current Regimen Line not displayed on new pharmacy form and care card.

### ISSUE THREAD

**Issue by Nnalda** [nmrs-nigeria/openmrs-module-nmrsmetadata#7]
Patient Current Regimen, Last Pick Up Date, Treatment Age, and Current Regimen Line are not displayed on pharmacy and care card forms to enable data entry clerks to ensure consistency with the previously prescribed regimen and or last pick update unless there is an actual switch or interruption.
The solution is to include Patient Current Regimen, Last Pick Up Date, Treatment Age, and Current Regimen Line to display on new pharmacy forms and care cards before new entries are made.

SOLUTION:
A field set was added to pharmacy form and care card to display patients last dispensed regimen, last pick update, last line and last treatment age

**Comment by teggsdgreat** [comment]
Patient Current Regimen, Last Pick Up Date, Treatment Age, and Current Regimen Line now can be seen on the pharmacy form and care card
