### ISSUE TITLE
Some regimen disparity between data captured on pharmacy form and those save in the database

### ISSUE THREAD

**Issue by Nnalda** [nmrs-nigeria/openmrs-module-nmrsmetadata#9]
It has been observed that when the patient line list is pulled regimens like ABC-3TC-LPV/r on pharmacy form come out as AZT-3TC-NVP from the database. The solution is to review concept ids for regimens and drugs to ensure alignment between pharmacy form and database. 

SOLUTION:
This issue was discovered not be NMRS specific but a problem with the SQL scripts used to generate line list. After updating the SQL scripts the issue was resolved.

**Comment by teggsdgreat** [comment]
there were no disparity in the database but wrong arrangement of regimen that were fixed
